// <auto-generated />
using System;
using GestaoProjetos.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoProjetos.DAL.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20180829000346_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.CargoDAO", b =>
                {
                    b.Property<long>("Id_Cargo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.HasKey("Id_Cargo");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.ColaboradorDAO", b =>
                {
                    b.Property<long>("Id_Colaborador")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CargoId_Cargo");

                    b.Property<string>("Nome");

                    b.HasKey("Id_Colaborador");

                    b.HasIndex("CargoId_Cargo");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.ColaboradorTarefaDAO", b =>
                {
                    b.Property<long>("ID_ColaboradorTarefa")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ColaboradorId_Colaborador");

                    b.Property<double>("Horas_Estimadas");

                    b.Property<long?>("TarefaId_Tarefa");

                    b.HasKey("ID_ColaboradorTarefa");

                    b.HasIndex("ColaboradorId_Colaborador");

                    b.HasIndex("TarefaId_Tarefa");

                    b.ToTable("ColaboradorTarefa");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.HorasColaboradorDAO", b =>
                {
                    b.Property<long>("Id_HorasColaborador")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ColaboradorId_Colaborador");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao");

                    b.Property<double>("Horas");

                    b.Property<long?>("TarefaId_Tarefa");

                    b.HasKey("Id_HorasColaborador");

                    b.HasIndex("ColaboradorId_Colaborador");

                    b.HasIndex("TarefaId_Tarefa");

                    b.ToTable("HorasColaborador");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.ProjetoDAO", b =>
                {
                    b.Property<long>("Id_Projeto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ");

                    b.Property<DateTime>("Data_Inicial_Contrato");

                    b.Property<double>("Horas_Projeto");

                    b.Property<string>("Observacoes");

                    b.Property<string>("Razao_Social");

                    b.HasKey("Id_Projeto");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.TarefaDAO", b =>
                {
                    b.Property<long>("Id_Tarefa")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Abertura");

                    b.Property<DateTime>("Data_Entrega");

                    b.Property<string>("Descricao");

                    b.Property<string>("Observacao");

                    b.Property<long?>("ProjetoId_Projeto");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.HasKey("Id_Tarefa");

                    b.HasIndex("ProjetoId_Projeto");

                    b.ToTable("Tarefa");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.ColaboradorDAO", b =>
                {
                    b.HasOne("GestaoProjetos.DAL.Entidades.CargoDAO", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId_Cargo");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.ColaboradorTarefaDAO", b =>
                {
                    b.HasOne("GestaoProjetos.DAL.Entidades.ColaboradorDAO", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId_Colaborador");

                    b.HasOne("GestaoProjetos.DAL.Entidades.TarefaDAO", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaId_Tarefa");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.HorasColaboradorDAO", b =>
                {
                    b.HasOne("GestaoProjetos.DAL.Entidades.ColaboradorDAO", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId_Colaborador");

                    b.HasOne("GestaoProjetos.DAL.Entidades.TarefaDAO", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaId_Tarefa");
                });

            modelBuilder.Entity("GestaoProjetos.DAL.Entidades.TarefaDAO", b =>
                {
                    b.HasOne("GestaoProjetos.DAL.Entidades.ProjetoDAO", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId_Projeto");
                });
#pragma warning restore 612, 618
        }
    }
}
